# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'
#
#
#- script: echo Hello, world!
#  displayName: 'Run a one-line script 1'
#
#
#- script: echo Hello, world!
#  displayName: 'Run a one-line script 2'
#
#- script: echo Hello, world!
#  displayName: 'Run a one-line script 3'
#
#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'


- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool:
      vmImage: 'Ubuntu-16.04'
    # creates an environment if it doesn't exist
    environment: 'xiaoming-dev'
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world